export const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000';
export const API_BASE_URL = `${API_URL}`;

export const ENDPOINTS = {
AUTH: {
    LOGIN: '/api/auth/login',
    REGISTER: '/api/auth/register',
    LOGOUT: '/api/auth/logout',
    REFRESH: '/api/auth/refresh',
    ME: '/api/auth/me',
    AVATAR: '/api/auth/avatar',
  },
  JOBS: {
    LIST: '/api/jobs',
    CREATE: '/api/jobs',
    DETAIL: (id: string) => `/api/jobs/${id}`,
    UPDATE: (id: string) => `/api/jobs/${id}`,
    DELETE: (id: string) => `/api/jobs/${id}`,
    BIAS: (id: string) => `/api/jobs/${id}/bias`,
    STATS: (id: string) => `/api/jobs/${id}/stats`,
    ALL: '/api/jobs/all',
  },
  APPLICANTS: {
    LIST: '/api/applicants',
    PROFILE: '/api/applicants/profile',
    UPLOAD: '/api/applicants/upload',
    MY_APPLICATIONS: '/api/applicants/internal/my-applications',
    MY_CV: (appId: string) => `/api/applicants/internal/my-cv/${appId}`,
    EXTERNAL: '/api/applicants/external',
    EXTERNAL_BULK_DELETE: '/api/applicants/external/bulk-delete',
    EXTERNAL_DETAIL: (id: string) => `/api/applicants/external/${id}`,
    EXTERNAL_STATUS: (id: string) => `/api/applicants/external/${id}/status`,
    EXTERNAL_TEMPLATE: '/api/applicants/external/template',
    EXTERNAL_PREVIEW: '/api/applicants/external/preview',
    EXTERNAL_UPLOAD_BULK: '/api/applicants/external/upload-bulk',
    INTERNAL: '/api/applicants/internal',
    INTERNAL_DETAIL: (id: string) => `/api/applicants/internal/${id}`,
    INTERNAL_STATUS: (id: string) => `/api/applicants/internal/${id}/status`,
    INTERNAL_CV: (applicationId: string) => `/api/applicants/internal/${applicationId}/cv`,
    INTERNAL_UPLOAD_RESUME: '/api/applicants/internal/upload-resume',
  },
  SCREENING: {
    LIST: '/api/screening',
    RUN: '/api/screening/run',
    RESULTS: (jobId: string) => `/api/screening/results/${jobId}`,
    STATS: (jobId: string) => `/api/screening/stats/${jobId}`,
    SHORTLISTED: (jobId: string) => `/api/screening/shortlisted/${jobId}`,
    COMPARE: '/api/screening/compare',
    RERUN: (jobId: string) => `/api/screening/rerun/${jobId}`,
  },
  ANALYTICS: {
    LIST: '/api/analytics',
    JOB: (jobId: string) => `/api/analytics/jobs/${jobId}`,
    APPLICANT: (applicantId: string) => `/api/analytics/applicants/${applicantId}`,
  },
  CHAT: {
    LIST: '/api/chat',
    CREATE: '/api/chat',
    GET_BY_ID: (chatId: string) => `/api/chat/${chatId}`,
    DELETE: (chatId: string) => `/api/chat/${chatId}`,
    MESSAGE: '/api/chat/message',
    RECOMMENDATIONS: '/api/chat/recommendations',
    ANALYZE: (jobId: string) => `/api/chat/analyze/${jobId}`,
  },
  SHORTLIST: {
    LIST: '/api/shortlist',
    JOB: (jobId: string) => `/api/shortlist/jobs/${jobId}`,
    COMPARE: '/api/shortlist/compare',
    EXPLAIN: (resultId: string) => `/api/shortlist/explain/${resultId}`,
  },
  AI: {
    ASSISTANT: '/api/ai/assistant',
    GUEST: '/api/ai/guest',
  },
  ADMIN: {
    DASHBOARD: '/api/admin/dashboard',
    USERS: '/api/admin/users',
    CREATE_USER: '/api/admin/create-user',
    UPDATE_USER_ROLE: (id: string) => `/api/admin/users/${id}/role`,
    DEACTIVATE_USER: '/api/admin/users/deactivate',
    REACTIVATE_USER: '/api/admin/users/reactivate',
    JOBS: '/api/admin/jobs',
    SETTINGS: '/api/admin/settings',
    ANALYTICS: '/api/admin/analytics',
  },
} as const;
